name: CI

on:
  push:
    branches: [ "main", "dev", "sp1-new", "sp1" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 1

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    # Change to warp-ubuntu-latest-x64-16x for a more powerful runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: argumentcomputer/ci-workflows
      - uses: ./.github/actions/ci-env
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@nextest
      - uses: Swatinem/rust-cache@v2
      - name: Linux Tests
        run: |
          cargo nextest run --profile ci --workspace
      - name: Linux Tests with the parallel feeature
        run: |
          cargo nextest run --profile ci --workspace --features parallel

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: argumentcomputer/ci-workflows
      - uses: ./.github/actions/ci-env
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Check Rustfmt Code Style
        run: cargo fmt --all --check
      - name: check *everything* compiles
        run: cargo check --all-targets --all-features --workspace --examples --tests --benches
      # See '.cargo/config' for list of enabled/disabled clippy lints
      - name: Check clippy warnings
        run: cargo xclippy -D warnings
      - name: Doctests
        run: cargo test --doc --workspace

  # On a push or pull request to `sp1-new` or `sp1`, check downstream crates compile
  check-downstream-compiles:
    runs-on: warp-ubuntu-latest-x64-16x
    if: ${{ github.base_ref == 'sp1-new' || github.ref_name == 'sp1-new' || github.base_ref == 'sp1' || github.ref_name == 'sp1' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - repo: sphinx
          - repo: loam
    steps:
      - uses: actions/checkout@v4
        with:
          repository: argumentcomputer/ci-workflows
          path: ci-workflows
      - uses: ./ci-workflows/.github/actions/ci-env
      - uses: actions/checkout@v4
        with:
          path: ${{ github.workspace }}/Plonky3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: actions/checkout@v4
        with:
          repository: argumentcomputer/${{ matrix.repo }}
          path: ${{ github.workspace }}/${{ matrix.repo }}
          token: ${{ secrets.REPO_TOKEN }}
      - uses: ./ci-workflows/.github/actions/check-downstream-compiles
        with:
          upstream-path: "Plonky3"
          downstream-path: "${{ matrix.repo }}"
          features: "${{ matrix.features }}"
