on:
  schedule:
  - cron:  "*/15 * * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    name: Sync changes from upstream SP1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://github.com/Plonky3/Plonky3.git"
        source_branch: "main"
        destination_branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}
